name: Learning GitHub Script

on:
  issues:
    types: [opened]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":tada: You've created this issue comment using GitHub Script!!!"
            })
            
      - name: Add isue to project board
        if: contains(github.event.issue.lables.*.name, 'bug')
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.projects.creatCard({
            column_id: 14221504,
            content_id: context.payload.issue.id,
            content_type: "Issue"
            });
